services:
  backend:
    image: ghcr.io/livegrep/livegrep/base
    networks:
      - livegrep
    volumes:
      - livegrep-data:/data
    command: /livegrep/bin/codesearch -load_index /data/livegrep.idx -grpc 0.0.0.0:9999

  frontend:
    image: ghcr.io/livegrep/livegrep/base
    networks:
      - livegrep
    ports:
      - "8910:8910"
    command: /livegrep/bin/livegrep -docroot /livegrep/web -listen=0.0.0.0:8910 --connect backend:9999

volumes:
  livegrep-data:

networks:
  livegrep:
