/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.BibliographicEntry;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;

import java.util.List;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-05-17T22:32:28.625814+03:00[Europe/Moscow]", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "api", description = "the api API")
public interface Api {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /api/books : Get all entries
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "apiBooksGet",
        summary = "Get all entries",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = BibliographicEntry.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/books",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<BibliographicEntry>> apiBooksGet(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"pages\" : 1, \"year\" : 6, \"isbn\" : \"isbn\", \"publisher\" : \"publisher\", \"id\" : 0, \"title\" : \"title\", \"authors\" : \"authors\" }, { \"pages\" : 1, \"year\" : 6, \"isbn\" : \"isbn\", \"publisher\" : \"publisher\", \"id\" : 0, \"title\" : \"title\", \"authors\" : \"authors\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /api/books/{id} : Delete entry
     *
     * @param id  (required)
     * @return Deleted (status code 204)
     */
    @Operation(
        operationId = "apiBooksIdDelete",
        summary = "Delete entry",
        responses = {
            @ApiResponse(responseCode = "204", description = "Deleted")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/books/{id}"
    )
    
    default ResponseEntity<Void> apiBooksIdDelete(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/books/{id} : Get entry by ID
     *
     * @param id  (required)
     * @return OK (status code 200)
     *         or Not found (status code 404)
     */
    @Operation(
        operationId = "apiBooksIdGet",
        summary = "Get entry by ID",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BibliographicEntry.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/books/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<BibliographicEntry> apiBooksIdGet(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"pages\" : 1, \"year\" : 6, \"isbn\" : \"isbn\", \"publisher\" : \"publisher\", \"id\" : 0, \"title\" : \"title\", \"authors\" : \"authors\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /api/books : Create new entry
     *
     * @param bibliographicEntry  (required)
     * @return Created (status code 201)
     */
    @Operation(
        operationId = "apiBooksPost",
        summary = "Create new entry",
        responses = {
            @ApiResponse(responseCode = "201", description = "Created")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/books",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> apiBooksPost(
        @Parameter(name = "BibliographicEntry", description = "", required = true) @Valid @RequestBody BibliographicEntry bibliographicEntry
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
